###############################
# MangoHud - Catppuccin Mocha
###############################

#vsync=1
#fps_limit=20
frame_timing=1
fps=1
frametime=1
gpu_stats=1
cpu_stats=1
gpu_temp=1
cpu_temp=1
gpu_vram=1
ram=1

fps_format="FPS: {fps}"
frametime_format="FT: {frametime}"
gpu_format="GPU: {gpu} {gpu_temp}°C"
cpu_format="CPU: {cpu} {cpu_temp}°C"
vram_format="VRAM: {vram}"
ram_format="RAM: {ram}"

position=top-left
offset_x=10
offset_y=10

background_alpha=0.6
background_color=1E1E2E
text_color=CDD6F4
fps_color=CDD6F4
frametime_color=F9E2AF
gpu_color=89B4FA
cpu_color=FAB387
vram_color=A6E3A1
ram_color=A6E3A1
temperature_color=F38BA8

font_size=20

legacy_layout=false
io_read=0
io_write=0
battery=0
network=0

gpu_text=GPU
cpu_text=CPU
vram_text=VRAM
ram_text=RAM
